name: Build and Push Image to Dockerhub and GHCR

on:
  push:
    branches: 
    - main
    - Hargata/745
  release:
    types: ["published"]
  workflow_dispatch:
    
permissions:
  contents: read
  packages: write
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          context: workflow
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/lubelogger
            ghcr.io/${{ github.actor }}/lubelogger
          tags: |
            type=edge,branch=main
            type=ref,event=tag
            type=edge,branch=Hargata/745

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
